name: Run Python Script Every Hour

on:
  schedule:
    - cron: '30 9 * * *'  # Jeden Tag um 09:30 Uhr
    - cron: '20 11 * * *' # Jeden Tag um 11:20 Uhr
    - cron: '15 12 * * *' # Jeden Tag um 12:15 Uhr
    - cron: '55 12 * * *' # Jeden Tag um 12:55 Uhr
    - cron: '0 14 * * *'  # Jeden Tag um 14:00 Uhr
    - cron: '0 15 * * *'  # Jeden Tag um 15:00 Uhr

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Abhängigkeiten installieren
        run: pip install -r requirements.txt  # Falls dein Skript Bibliotheken benötigt

      - name: Skript ausführen
        run: python crawler.py  # Ersetze mit dem Namen deines Skripts
